<Project>
  <PropertyGroup>
    <VersionPrefix>0.17.1</VersionPrefix>
    <VersionSuffix>beta</VersionSuffix>
    <Version>$(VersionPrefix)-$(VersionSuffix)</Version>
    <AssemblyVersion>0.17.1.0</AssemblyVersion>
    <FileVersion>0.17.1.0</FileVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <AppxPackageVersion>0.17.1.0</AppxPackageVersion>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
