using Microsoft.Data.Sqlite;
using SeminarSched.Application.Scheduling;
using SeminarSched.Infrastructure.Projects;

namespace SeminarSched.Infrastructure.Scheduling;

public sealed class SqliteFixedLessonService : IFixedLessonService
{
    public async Task<IReadOnlyList<LessonRequestOption>> GetRequestsAsync(string p,CancellationToken t=default){await using var c=await Open(p,t);await Ensure(c,t);await using var q=c.CreateCommand();q.CommandText="SELECT r.Id,r.StudentId,s.ExternalId||' '||s.Name||' / '||sub.DisplayName FROM LessonRequest r JOIN Student s ON s.Id=r.StudentId JOIN Subject sub ON sub.Id=r.SubjectId ORDER BY s.ExternalId,sub.SortOrder;";var x=new List<LessonRequestOption>();await using var d=await q.ExecuteReaderAsync(t);while(await d.ReadAsync(t))x.Add(new(d.GetInt64(0),d.GetInt64(1),d.GetString(2)));return x;}
    public async Task<IReadOnlyList<TeacherOption>> GetTeachersAsync(string p,CancellationToken t=default){await using var c=await Open(p,t);await Ensure(c,t);await using var q=c.CreateCommand();q.CommandText="SELECT Id,ExternalId||' '||Name FROM Teacher WHERE Active=1 ORDER BY ExternalId;";var x=new List<TeacherOption>();await using var d=await q.ExecuteReaderAsync(t);while(await d.ReadAsync(t))x.Add(new(d.GetInt64(0),d.GetString(1)));return x;}
    public async Task<IReadOnlyList<ScheduleSlotOption>> GetSlotsAsync(string p,CancellationToken t=default){await using var c=await Open(p,t);await Ensure(c,t);await using var q=c.CreateCommand();q.CommandText="SELECT d.Id,s.Id,d.Date||' '||s.DisplayName||' ('||s.StartTime||'-'||s.EndTime||')' FROM OpenDate d JOIN OpenDateTimeSlot ds ON ds.OpenDateId=d.Id JOIN TimeSlot s ON s.Id=ds.TimeSlotId WHERE d.IsOpen=1 AND s.Active=1 ORDER BY d.Date,s.SortOrder;";var x=new List<ScheduleSlotOption>();await using var d=await q.ExecuteReaderAsync(t);while(await d.ReadAsync(t))x.Add(new(d.GetInt64(0),d.GetInt64(1),d.GetString(2)));return x;}
    public async Task<IReadOnlyList<FixedLesson>> GetFixedLessonsAsync(string p,CancellationToken t=default){await using var c=await Open(p,t);await Ensure(c,t);await using var q=c.CreateCommand();q.CommandText="SELECT a.Id,a.LessonRequestId,a.TeacherId,a.OpenDateId,a.TimeSlotId,d.Date||' '||ts.DisplayName||' / '||s.Name||' / '||te.Name FROM Assignment a JOIN LessonRequest r ON r.Id=a.LessonRequestId JOIN Student s ON s.Id=r.StudentId JOIN Teacher te ON te.Id=a.TeacherId JOIN OpenDate d ON d.Id=a.OpenDateId JOIN TimeSlot ts ON ts.Id=a.TimeSlotId WHERE a.IsLocked=1 ORDER BY d.Date,ts.SortOrder;";var x=new List<FixedLesson>();await using var d=await q.ExecuteReaderAsync(t);while(await d.ReadAsync(t))x.Add(new(d.GetInt64(0),d.GetInt64(1),d.GetInt64(2),d.GetInt64(3),d.GetInt64(4),d.GetString(5)));return x;}
    public async Task AddAsync(string p,long request,long teacher,long date,long slot,CancellationToken t=default){await using var c=await Open(p,t);await Ensure(c,t);await using var tx=await c.BeginTransactionAsync(t);await using var validate=c.CreateCommand();validate.Transaction=(SqliteTransaction)tx;validate.CommandText="SELECT r.StudentId,r.SubjectId FROM LessonRequest r WHERE r.Id=@r AND EXISTS(SELECT 1 FROM OpenDateTimeSlot ds JOIN OpenDate d ON d.Id=ds.OpenDateId WHERE ds.OpenDateId=@d AND ds.TimeSlotId=@s AND d.IsOpen=1);";validate.Parameters.AddWithValue("@r",request);validate.Parameters.AddWithValue("@d",date);validate.Parameters.AddWithValue("@s",slot);await using var reader=await validate.ExecuteReaderAsync(t);if(!await reader.ReadAsync(t))throw new InvalidOperationException("受講希望または開校コマが無効です。");var student=reader.GetInt64(0);var subject=reader.GetInt64(1);await reader.DisposeAsync();
        await using var conflict=c.CreateCommand();conflict.Transaction=(SqliteTransaction)tx;conflict.CommandText="SELECT EXISTS(SELECT 1 FROM Assignment a JOIN LessonRequest r ON r.Id=a.LessonRequestId WHERE a.OpenDateId=@d AND a.TimeSlotId=@s AND (a.TeacherId=@t OR r.StudentId=@student));";conflict.Parameters.AddWithValue("@d",date);conflict.Parameters.AddWithValue("@s",slot);conflict.Parameters.AddWithValue("@t",teacher);conflict.Parameters.AddWithValue("@student",student);if(Convert.ToInt64(await conflict.ExecuteScalarAsync(t))==1)throw new InvalidOperationException("同じ日時に生徒または講師の授業が既にあります。");
        await using var qualification=c.CreateCommand();qualification.Transaction=(SqliteTransaction)tx;qualification.CommandText="SELECT COALESCE((SELECT CanTeach FROM TeacherQualification WHERE TeacherId=@t AND SubjectId=@s),0);";qualification.Parameters.AddWithValue("@t",teacher);qualification.Parameters.AddWithValue("@s",subject);var can=await qualification.ExecuteScalarAsync(t);if(Convert.ToInt64(can)==0)throw new InvalidOperationException("この講師は科目を担当可能に設定されていません。");
        await using var add=c.CreateCommand();add.Transaction=(SqliteTransaction)tx;add.CommandText="INSERT INTO Assignment(LessonRequestId,TeacherId,OpenDateId,TimeSlotId,IsLocked,Source) VALUES(@r,@t,@d,@s,1,'preconfirmed');";add.Parameters.AddWithValue("@r",request);add.Parameters.AddWithValue("@t",teacher);add.Parameters.AddWithValue("@d",date);add.Parameters.AddWithValue("@s",slot);await add.ExecuteNonQueryAsync(t);await tx.CommitAsync(t);}
    public async Task RemoveAsync(string p,long id,CancellationToken t=default){await using var c=await Open(p,t);await Ensure(c,t);await using var q=c.CreateCommand();q.CommandText="DELETE FROM Assignment WHERE Id=@id AND IsLocked=1;";q.Parameters.AddWithValue("@id",id);await q.ExecuteNonQueryAsync(t);}
    private static async Task<SqliteConnection> Open(string p,CancellationToken t){var c=new SqliteConnection(new SqliteConnectionStringBuilder{DataSource=Path.GetFullPath(p),Mode=SqliteOpenMode.ReadWrite,ForeignKeys=true,Pooling=false}.ToString());await c.OpenAsync(t);return c;}
    private static Task Ensure(SqliteConnection connection, CancellationToken cancellationToken) =>
        SqliteProjectSchema.EnsureCurrentAsync(connection, cancellationToken);
}
